import {
  Award,
  BadgeCheck,
  BookOpen,
  CalendarCheck,
  Camera,
  Compass,
  Crown,
  Droplets,
  Earth,
  Flame,
  Footprints,
  GraduationCap,
  Handshake,
  Leaf,
  Map as MapIcon,
  MapPin,
  Megaphone,
  Search,
  Share2,
  Shield,
  ShieldCheck,
  Sparkles,
  Sprout,
  Trash2,
  Trees,
  Trophy,
  Users,
  Waves,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  award: Award,
  "badge-check": BadgeCheck,
  "book-open": BookOpen,
  "calendar-check": CalendarCheck,
  camera: Camera,
  compass: Compass,
  crown: Crown,
  droplets: Droplets,
  earth: Earth,
  flame: Flame,
  footprints: Footprints,
  globe: Earth,
  "graduation-cap": GraduationCap,
  handshake: Handshake,
  leaf: Leaf,
  map: MapIcon,
  "map-pin": MapPin,
  megaphone: Megaphone,
  search: Search,
  "share-2": Share2,
  shield: Shield,
  "shield-check": ShieldCheck,
  sparkles: Sparkles,
  sprout: Sprout,
  "trash-2": Trash2,
  trees: Trees,
  trophy: Trophy,
  users: Users,
  waves: Waves,
  zap: Zap,
};

export function iconByName(name: string | null | undefined): LucideIcon {
  return ICONS[name ?? ""] ?? Award;
}
