/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedConquistasRouteImport } from './routes/_authenticated/conquistas'
import { Route as AuthenticatedDenunciarRouteImport } from './routes/_authenticated/denunciar'
import { Route as AuthenticatedDesafiosRouteImport } from './routes/_authenticated/desafios'
import { Route as AuthenticatedDicasRouteImport } from './routes/_authenticated/dicas'
import { Route as AuthenticatedEditarPerfilRouteImport } from './routes/_authenticated/editar-perfil'
import { Route as AuthenticatedLojaRouteImport } from './routes/_authenticated/loja'
import { Route as AuthenticatedMapaRouteImport } from './routes/_authenticated/mapa'
import { Route as AuthenticatedMinhasDenunciasRouteImport } from './routes/_authenticated/minhas-denuncias'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated/ranking'
import { Route as AuthenticatedDenunciaIdRouteImport } from './routes/_authenticated/denuncia.$id'
import { Route as AuthenticatedAdminDenunciaIdRouteImport } from './routes/_authenticated/admin.denuncia.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConquistasRoute = AuthenticatedConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDenunciarRoute = AuthenticatedDenunciarRouteImport.update({
  id: '/denunciar',
  path: '/denunciar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesafiosRoute = AuthenticatedDesafiosRouteImport.update({
  id: '/desafios',
  path: '/desafios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDicasRoute = AuthenticatedDicasRouteImport.update({
  id: '/dicas',
  path: '/dicas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEditarPerfilRoute =
  AuthenticatedEditarPerfilRouteImport.update({
    id: '/editar-perfil',
    path: '/editar-perfil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLojaRoute = AuthenticatedLojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapaRoute = AuthenticatedMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhasDenunciasRoute =
  AuthenticatedMinhasDenunciasRouteImport.update({
    id: '/minhas-denuncias',
    path: '/minhas-denuncias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDenunciaIdRoute = AuthenticatedDenunciaIdRouteImport.update({
  id: '/denuncia/$id',
  path: '/denuncia/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminDenunciaIdRoute =
  AuthenticatedAdminDenunciaIdRouteImport.update({
    id: '/denuncia/$id',
    path: '/denuncia/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/conquistas': typeof AuthenticatedConquistasRoute
  '/denunciar': typeof AuthenticatedDenunciarRoute
  '/desafios': typeof AuthenticatedDesafiosRoute
  '/dicas': typeof AuthenticatedDicasRoute
  '/editar-perfil': typeof AuthenticatedEditarPerfilRoute
  '/loja': typeof AuthenticatedLojaRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/minhas-denuncias': typeof AuthenticatedMinhasDenunciasRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/denuncia/$id': typeof AuthenticatedDenunciaIdRoute
  '/admin/denuncia/$id': typeof AuthenticatedAdminDenunciaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/conquistas': typeof AuthenticatedConquistasRoute
  '/denunciar': typeof AuthenticatedDenunciarRoute
  '/desafios': typeof AuthenticatedDesafiosRoute
  '/dicas': typeof AuthenticatedDicasRoute
  '/editar-perfil': typeof AuthenticatedEditarPerfilRoute
  '/loja': typeof AuthenticatedLojaRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/minhas-denuncias': typeof AuthenticatedMinhasDenunciasRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/denuncia/$id': typeof AuthenticatedDenunciaIdRoute
  '/admin/denuncia/$id': typeof AuthenticatedAdminDenunciaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/conquistas': typeof AuthenticatedConquistasRoute
  '/_authenticated/denunciar': typeof AuthenticatedDenunciarRoute
  '/_authenticated/desafios': typeof AuthenticatedDesafiosRoute
  '/_authenticated/dicas': typeof AuthenticatedDicasRoute
  '/_authenticated/editar-perfil': typeof AuthenticatedEditarPerfilRoute
  '/_authenticated/loja': typeof AuthenticatedLojaRoute
  '/_authenticated/mapa': typeof AuthenticatedMapaRoute
  '/_authenticated/minhas-denuncias': typeof AuthenticatedMinhasDenunciasRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/denuncia/$id': typeof AuthenticatedDenunciaIdRoute
  '/_authenticated/admin/denuncia/$id': typeof AuthenticatedAdminDenunciaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/criar-conta'
    | '/entrar'
    | '/redefinir-senha'
    | '/admin'
    | '/app'
    | '/conquistas'
    | '/denunciar'
    | '/desafios'
    | '/dicas'
    | '/editar-perfil'
    | '/loja'
    | '/mapa'
    | '/minhas-denuncias'
    | '/notificacoes'
    | '/perfil'
    | '/ranking'
    | '/denuncia/$id'
    | '/admin/denuncia/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/criar-conta'
    | '/entrar'
    | '/redefinir-senha'
    | '/admin'
    | '/app'
    | '/conquistas'
    | '/denunciar'
    | '/desafios'
    | '/dicas'
    | '/editar-perfil'
    | '/loja'
    | '/mapa'
    | '/minhas-denuncias'
    | '/notificacoes'
    | '/perfil'
    | '/ranking'
    | '/denuncia/$id'
    | '/admin/denuncia/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/criar-conta'
    | '/entrar'
    | '/redefinir-senha'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/conquistas'
    | '/_authenticated/denunciar'
    | '/_authenticated/desafios'
    | '/_authenticated/dicas'
    | '/_authenticated/editar-perfil'
    | '/_authenticated/loja'
    | '/_authenticated/mapa'
    | '/_authenticated/minhas-denuncias'
    | '/_authenticated/notificacoes'
    | '/_authenticated/perfil'
    | '/_authenticated/ranking'
    | '/_authenticated/denuncia/$id'
    | '/_authenticated/admin/denuncia/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CriarContaRoute: typeof CriarContaRoute
  EntrarRoute: typeof EntrarRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conquistas': {
      id: '/_authenticated/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof AuthenticatedConquistasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/denunciar': {
      id: '/_authenticated/denunciar'
      path: '/denunciar'
      fullPath: '/denunciar'
      preLoaderRoute: typeof AuthenticatedDenunciarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desafios': {
      id: '/_authenticated/desafios'
      path: '/desafios'
      fullPath: '/desafios'
      preLoaderRoute: typeof AuthenticatedDesafiosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dicas': {
      id: '/_authenticated/dicas'
      path: '/dicas'
      fullPath: '/dicas'
      preLoaderRoute: typeof AuthenticatedDicasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/editar-perfil': {
      id: '/_authenticated/editar-perfil'
      path: '/editar-perfil'
      fullPath: '/editar-perfil'
      preLoaderRoute: typeof AuthenticatedEditarPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loja': {
      id: '/_authenticated/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof AuthenticatedLojaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapa': {
      id: '/_authenticated/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AuthenticatedMapaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minhas-denuncias': {
      id: '/_authenticated/minhas-denuncias'
      path: '/minhas-denuncias'
      fullPath: '/minhas-denuncias'
      preLoaderRoute: typeof AuthenticatedMinhasDenunciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/denuncia/$id': {
      id: '/_authenticated/denuncia/$id'
      path: '/denuncia/$id'
      fullPath: '/denuncia/$id'
      preLoaderRoute: typeof AuthenticatedDenunciaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/denuncia/$id': {
      id: '/_authenticated/admin/denuncia/$id'
      path: '/denuncia/$id'
      fullPath: '/admin/denuncia/$id'
      preLoaderRoute: typeof AuthenticatedAdminDenunciaIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDenunciaIdRoute: typeof AuthenticatedAdminDenunciaIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDenunciaIdRoute: AuthenticatedAdminDenunciaIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedConquistasRoute: typeof AuthenticatedConquistasRoute
  AuthenticatedDenunciarRoute: typeof AuthenticatedDenunciarRoute
  AuthenticatedDesafiosRoute: typeof AuthenticatedDesafiosRoute
  AuthenticatedDicasRoute: typeof AuthenticatedDicasRoute
  AuthenticatedEditarPerfilRoute: typeof AuthenticatedEditarPerfilRoute
  AuthenticatedLojaRoute: typeof AuthenticatedLojaRoute
  AuthenticatedMapaRoute: typeof AuthenticatedMapaRoute
  AuthenticatedMinhasDenunciasRoute: typeof AuthenticatedMinhasDenunciasRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedDenunciaIdRoute: typeof AuthenticatedDenunciaIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedConquistasRoute: AuthenticatedConquistasRoute,
  AuthenticatedDenunciarRoute: AuthenticatedDenunciarRoute,
  AuthenticatedDesafiosRoute: AuthenticatedDesafiosRoute,
  AuthenticatedDicasRoute: AuthenticatedDicasRoute,
  AuthenticatedEditarPerfilRoute: AuthenticatedEditarPerfilRoute,
  AuthenticatedLojaRoute: AuthenticatedLojaRoute,
  AuthenticatedMapaRoute: AuthenticatedMapaRoute,
  AuthenticatedMinhasDenunciasRoute: AuthenticatedMinhasDenunciasRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedDenunciaIdRoute: AuthenticatedDenunciaIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CriarContaRoute: CriarContaRoute,
  EntrarRoute: EntrarRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
